apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    app: todo-chatbot
type: Opaque
stringData:
  AUTH_SECRET: {{ .Values.secret.authSecret | quote }}
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  GROQ_API_KEY: {{ .Values.secret.groqApiKey | quote }}
